import os
import re
import math
from pathlib import Path
from db import get_supabase
from postgrest.exceptions import APIError

KNOWLEDGE_DIR = Path(__file__).resolve().parent / "knowledge"

CREATE_KNOWLEDGE_TABLE_SQL = """-- Script SQL tạo bảng knowledge_base lưu trữ tài liệu RAG trên Supabase:
CREATE TABLE IF NOT EXISTS public.knowledge_base (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    section TEXT,
    content TEXT NOT NULL,
    tags TEXT[],
    source_file TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tạo chỉ mục tìm kiếm văn bản toàn phần (Full-Text Search) tiếng Việt / tiếng Anh
CREATE INDEX IF NOT EXISTS idx_knowledge_content_search 
ON public.knowledge_base 
USING gin(to_tsvector('simple', content));

-- Cấu hình quyền truy cập Service Role
ALTER TABLE public.knowledge_base ENABLE ROW LEVEL SECURITY;

CREATE POLICY IF NOT EXISTS "Service role knowledge access" 
ON public.knowledge_base 
FOR ALL 
TO service_role 
USING (true) 
WITH CHECK (true);
"""


class TravelRAG:
    """
    Hệ thống RAG (Retrieval-Augmented Generation) chuyên biệt cho đại lý du lịch (Travel Reseller).
    Quản lý kho tri thức điểm đến, giá vé, lịch trình, chính sách và truy xuất ngữ cảnh cho AI.
    """

    def __init__(self, knowledge_dir: Path = None):
        self.knowledge_dir = knowledge_dir or KNOWLEDGE_DIR
        self.chunks = []
        self._load_and_chunk_documents()

    def _load_and_chunk_documents(self):
        """
        Đọc tất cả các tài liệu từ thư mục knowledge và chia thành các đoạn ngữ nghĩa (chunks).
        """
        self.chunks = []
        if not self.knowledge_dir.exists():
            return

        for file_path in self.knowledge_dir.glob("*.md"):
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    content = f.read()

                # Trích xuất tiêu đề chính (h1)
                title_match = re.search(r"^#\s+(.+)$", content, re.MULTILINE)
                main_title = title_match.group(1).strip() if title_match else file_path.stem

                # Chia nhỏ theo các đề mục cấp 2 (##)
                sections = re.split(r"\n(?=##\s+)", content)
                for sec in sections:
                    sec = sec.strip()
                    if not sec:
                        continue

                    sec_title_match = re.search(r"^##\s+(.+)$", sec, re.MULTILINE)
                    sec_title = sec_title_match.group(1).strip() if sec_title_match else "Thông tin chung"

                    # Loại bỏ dòng tiêu đề khỏi nội dung chi tiết
                    clean_content = re.sub(r"^##\s+.+$", "", sec, flags=re.MULTILINE).strip()
                    if not clean_content:
                        continue

                    # Trích xuất tags từ từ khóa
                    tags = self._extract_tags(main_title + " " + sec_title)

                    self.chunks.append({
                        "title": main_title,
                        "section": sec_title,
                        "content": clean_content,
                        "full_text": f"[{main_title} - {sec_title}]\n{clean_content}",
                        "source": file_path.name,
                        "tags": tags
                    })
            except Exception as e:
                print(f"[RAG] Lỗi khi đọc file {file_path.name}: {e}")

    def _extract_tags(self, text: str) -> list:
        keywords = ["bà nà", "cầu vàng", "cù lao chàm", "hội an", "rừng dừa", "giá vé", "lịch trình", "buffet", "trẻ em", "cano", "san hô"]
        lower = text.lower()
        return [kw for kw in keywords if kw in lower]

    def _tokenize(self, text: str) -> list:
        """Tách từ đơn giản cho tiếng Việt / tiếng Anh"""
        return re.findall(r"\b[\w\u00C0-\u1EF9]+\b", text.lower())

    def retrieve(self, query: str, top_k: int = 3) -> list:
        """
        Truy xuất Top-K đoạn tri thức liên quan nhất dựa trên BM25 & Semantic Scoring.
        """
        if not self.chunks:
            self._load_and_chunk_documents()

        if not self.chunks:
            return []

        query_tokens = set(self._tokenize(query))
        if not query_tokens:
            return self.chunks[:top_k]

        scored_chunks = []
        for chunk in self.chunks:
            score = 0.0
            chunk_tokens = self._tokenize(chunk["full_text"])
            chunk_token_set = set(chunk_tokens)

            # 1. Điểm khớp từ vựng
            common = query_tokens.intersection(chunk_token_set)
            score += len(common) * 2.0

            # 2. Điểm khớp tiêu đề (Title match boost)
            title_tokens = set(self._tokenize(chunk["title"] + " " + chunk["section"]))
            title_common = query_tokens.intersection(title_tokens)
            score += len(title_common) * 5.0

            # 3. Điểm khớp cụm từ chính xác (Exact phrase match)
            query_lower = query.lower()
            if chunk["title"].lower() in query_lower or any(tag in query_lower for tag in chunk["tags"]):
                score += 8.0

            if score > 0:
                scored_chunks.append((score, chunk))

        # Sắp xếp theo điểm giảm dần
        scored_chunks.sort(key=lambda x: x[0], reverse=True)
        return [chunk for _, chunk in scored_chunks[:top_k]]

    def get_grounded_context(self, product_name: str, location: str = "", target_audience: str = "", top_k: int = 3) -> str:
        """
        Tạo đoạn văn bản ngữ cảnh thực tế (grounded context) để đưa vào prompt cho LLM.
        """
        search_query = f"{product_name} {location} {target_audience}"
        relevant_chunks = self.retrieve(search_query, top_k=top_k)

        if not relevant_chunks:
            return "Không tìm thấy dữ liệu tri thức riêng cho sản phẩm này."

        formatted_parts = []
        for i, c in enumerate(relevant_chunks, 1):
            formatted_parts.append(
                f"--- NGUỒN TRI THỨC #{i} [{c['title']} - {c['section']}] ---\n{c['content']}"
            )

        return "\n\n".join(formatted_parts)

    def sync_to_supabase(self) -> dict:
        """
        Đồng bộ kho tài liệu tri thức lên bảng knowledge_base trong Supabase.
        """
        try:
            supabase = get_supabase()
        except Exception as e:
            return {"success": False, "message": f"Không thể kết nối Supabase: {e}"}

        records = []
        for chunk in self.chunks:
            records.append({
                "title": chunk["title"],
                "section": chunk["section"],
                "content": chunk["content"],
                "tags": chunk["tags"],
                "source_file": chunk["source"]
            })

        if not records:
            return {"success": False, "message": "Kho tri thức địa phương đang trống."}

        try:
            res = supabase.table("knowledge_base").insert(records).execute()
            return {
                "success": True,
                "message": f"Đã đồng bộ {len(records)} mẩu tri thức RAG lên bảng 'knowledge_base' trên Supabase!",
                "count": len(records)
            }
        except APIError as api_err:
            err_msg = str(api_err)
            if "42P01" in err_msg or "relation \"knowledge_base\" does not exist" in err_msg.lower():
                return {
                    "success": False,
                    "message": "Bảng 'knowledge_base' chưa được tạo trong Supabase. Vui lòng chạy lệnh SQL tạo bảng.",
                    "sql_hint": CREATE_KNOWLEDGE_TABLE_SQL
                }
            return {"success": False, "message": f"Lỗi Supabase: {err_msg}"}
        except Exception as e:
            return {"success": False, "message": f"Lỗi không xác định: {e}"}


# Singleton instance toàn cục
rag_instance = TravelRAG()

def get_rag() -> TravelRAG:
    return rag_instance
