import config
from supabase import create_client, Client
from postgrest.exceptions import APIError
import httpx

CREATE_CONTENTS_TABLE_SQL = """-- 1. Nếu chưa có bảng contents, chạy lệnh tạo bảng mới:
CREATE TABLE IF NOT EXISTS public.contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id TEXT NOT NULL,
    product_id TEXT NOT NULL,
    persona TEXT DEFAULT 'general',
    hook TEXT,
    script TEXT,
    caption TEXT,
    cta TEXT,
    status TEXT DEFAULT 'pending_approval',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Nếu đã có bảng contents từ trước nhưng thiếu cột product_id hoặc cta:
ALTER TABLE public.contents ADD COLUMN IF NOT EXISTS product_id TEXT;
ALTER TABLE public.contents ADD COLUMN IF NOT EXISTS cta TEXT;

-- 3. Cấu hình phân quyền Service Role
ALTER TABLE public.contents ENABLE ROW LEVEL SECURITY;

CREATE POLICY IF NOT EXISTS "Service role full access" 
ON public.contents 
FOR ALL 
TO service_role 
USING (true) 
WITH CHECK (true);
"""

def get_supabase(url: str = None, key: str = None) -> Client:
    """
    Khởi tạo và trả về Supabase Client với kiểm tra tham số và try-catch.
    """
    target_url = url or config.SUPABASE_URL
    target_key = key or config.SUPABASE_KEY

    if not target_url or not target_key:
        raise ValueError(
            "Thiếu SUPABASE_URL hoặc SUPABASE_KEY! "
            "Vui lòng cấu hình trong file .env hoặc truyền trực tiếp vào hàm."
        )

    if "xxxxx.supabase.co" in target_url or "your_service_role_key_here" in target_key:
        raise ValueError(
            "SUPABASE_URL hoặc SUPABASE_KEY vẫn đang mang giá trị mẫu chưa thay thế. "
            "Vui lòng cập nhật key thật từ Supabase Dashboard."
        )

    try:
        return create_client(target_url, target_key)
    except Exception as e:
        raise RuntimeError(f"Không thể khởi tạo Supabase Client: {str(e)}") from e


def list_products() -> list[dict]:
    """Load the Supabase product catalog and normalize common schema names.

    The PRD schema uses ``name``/``booking_url`` while the Sheets prototype
    uses ``product_name``/``official_booking_url``. Accept both so the UI can
    work with either schema without requiring a database migration.
    """
    client = get_supabase()
    response = client.table("products").select("*").execute()
    rows = response.data or []

    merchant_names = {}
    # Product rows may store merchant_id instead of a denormalized name.
    try:
        merchants_response = client.table("merchants").select("*").execute()
        for merchant in merchants_response.data or []:
            merchant_id = merchant.get("id") or merchant.get("merchant_id")
            merchant_name = merchant.get("merchant_name") or merchant.get("name") or merchant.get("business_name")
            if merchant_id and merchant_name:
                merchant_names[str(merchant_id)] = str(merchant_name)
    except Exception:
        # Keep products usable if merchants has a different schema or policy.
        pass

    normalized = []
    for row in rows:
        product_id = row.get("product_id") or row.get("sku") or row.get("id")
        product_name = row.get("product_name") or row.get("name") or row.get("title")
        if not product_id or not product_name:
            continue

        merchant_value = row.get("merchant_name") or row.get("merchant")
        if isinstance(merchant_value, dict):
            merchant_value = merchant_value.get("merchant_name") or merchant_value.get("name")
        merchant_id = row.get("merchant_id")
        merchant_name = merchant_value or merchant_names.get(str(merchant_id), "")

        price = row.get("confirmed_price_offer")
        if price is None or price == "":
            price = row.get("sale_price")
        if price is None or price == "":
            price = row.get("price")

        normalized.append({
            "product_id": str(product_id),
            "product_name": str(product_name),
            "merchant_name": str(merchant_name or ""),
            "location": str(row.get("location") or row.get("destination") or ""),
            "verified_facts": str(row.get("verified_facts") or row.get("description") or row.get("short_description") or ""),
            "confirmed_price_offer": str(price or ""),
            "target_audience": str(row.get("target_audience") or row.get("audience") or ""),
            # The PRD schema has both booking_url and payment_url. Use
            # payment_url only as a fallback when no explicit booking URL is
            # populated; merchants should confirm it is a valid booking link.
            "official_booking_url": str(
                row.get("official_booking_url")
                or row.get("booking_url")
                or row.get("payment_url")
                or ""
            ),
            "active": row.get("active", row.get("status", "")),
        })

    return normalized

def test_supabase_connection(url: str = None, key: str = None) -> dict:
    """
    Kiểm tra toàn diện kết nối tới Supabase và tình trạng bảng 'contents'.
    Trả về dict:
    {
        "success": bool,
        "message": str,
        "table_exists": bool,
        "details": str,
        "sql_hint": str (nếu chưa có bảng)
    }
    """
    try:
        client = get_supabase(url, key)
    except ValueError as ve:
        return {
            "success": False,
            "message": f"Cấu hình chưa hợp lệ: {ve}",
            "table_exists": False,
            "details": str(ve),
            "sql_hint": None
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"Khởi tạo client thất bại: {e}",
            "table_exists": False,
            "details": str(e),
            "sql_hint": None
        }

    # Thử truy vấn bảng contents để kiểm tra kết nối và cấu trúc DB
    try:
        response = client.table("contents").select("*", count="exact").limit(1).execute()
        count = response.count if hasattr(response, "count") and response.count is not None else len(response.data)
        return {
            "success": True,
            "message": f"Kết nối Supabase thành công! Bảng 'contents' đã sẵn sàng (hiện có {count} bản ghi).",
            "table_exists": True,
            "details": f"Trạng thái kết nối tốt. Số lượng bản ghi kiểm tra: {count}",
            "sql_hint": None
        }
    except APIError as api_err:
        err_msg = str(api_err)
        err_code = getattr(api_err, "code", "")

        # Kiểm tra xem có phải do bảng contents chưa tồn tại không
        if "42P01" in err_msg or "relation \"contents\" does not exist" in err_msg.lower() or "not found" in err_msg.lower():
            return {
                "success": True,  # Key và URL đúng, chỉ thiếu bảng
                "message": "Kết nối Supabase thành công, nhưng bảng 'contents' chưa được tạo trong Database!",
                "table_exists": False,
                "details": f"Chi tiết lỗi từ Postgres: {err_msg}",
                "sql_hint": CREATE_CONTENTS_TABLE_SQL
            }
        elif "JWT" in err_msg or "Invalid API key" in err_msg or "unauthorized" in err_msg.lower():
            return {
                "success": False,
                "message": "Key Supabase không hợp lệ hoặc đã hết hạn (401/403). Hãy chắc chắn bạn dùng Service Role Key.",
                "table_exists": False,
                "details": f"APIError: {err_msg}",
                "sql_hint": None
            }
        else:
            return {
                "success": False,
                "message": f"Lỗi từ Supabase API: {err_msg}",
                "table_exists": False,
                "details": f"Code: {err_code} - {err_msg}",
                "sql_hint": None
            }
    except (httpx.ConnectError, httpx.HTTPError) as net_err:
        return {
            "success": False,
            "message": "Không thể kết nối đến URL Supabase. Vui lòng kiểm tra lại mạng hoặc SUPABASE_URL.",
            "table_exists": False,
            "details": f"Network Error: {str(net_err)}",
            "sql_hint": None
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"Lỗi không xác định khi kết nối Supabase: {str(e)}",
            "table_exists": False,
            "details": str(e),
            "sql_hint": None
        }
